export const enum Language {
  ChineseCN = "zh-cn",
  ChineseTW = "zh-tw",
  German = "de-de",
  EnglishUS = "en-us",
  SpanishES = "es-es",
  French = "fr-fr",
  Indonesia = "id-id",
  Japanese = "ja-jp",
  Korean = "ko-kr",
  Portuguese = "pt-pt",
  Russian = "ru-ru",
  Thai = "th-th",
  Vietnamese = "vi-vn",
}
